# -*- eval: (cargo-minor-mode 1) -*-

[workspace]
members = [".", "codegen"]

[package]
name = "svgwriter"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
indexmap = "1.9"
itoa = "1.0"
paste = "1.0"
