# -*- eval: (cargo-minor-mode 1) -*-

[package]
workspace = ".."
name = "svgwriter-codegen"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
askama = "0.11"
heck = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
